#include "../config.h"


static struct Raid sRoute1Raids1Star[] =
{
	{
		.species = SPECIES_PIKIPEK,
		.ability = RAID_ABILITY_RANDOM_1_2,
		.drops =
		{
			/*100 %*/ ITEM_SUPER_POTION,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 50 %*/ ITEM_NONE,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_POTION,
			/* 30 %*/ ITEM_POTION,
			/* 25 %*/ ITEM_NONE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_RARE_CANDY,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_NONE,
		},
	},
	{
		.species = SPECIES_HOOTHOOT,
		.ability = RAID_ABILITY_RANDOM_1_2,
		.drops =
		{
			/*100 %*/ ITEM_SUPER_POTION,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 50 %*/ ITEM_NONE,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_POTION,
			/* 30 %*/ ITEM_POTION,
			/* 25 %*/ ITEM_NONE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_RARE_CANDY,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_NONE,
		},
	},
	{
		.species = SPECIES_LILLIPUP,
		.ability = RAID_ABILITY_RANDOM_1_2,
		.drops =
		{
			/*100 %*/ ITEM_SUPER_POTION,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 50 %*/ ITEM_NONE,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_POTION,
			/* 30 %*/ ITEM_POTION,
			/* 25 %*/ ITEM_NONE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_RARE_CANDY,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_NONE,
		},
	},
	{
		.species = SPECIES_EKANS,
		.ability = RAID_ABILITY_RANDOM_1_2,
		.drops =
		{
			/*100 %*/ ITEM_PECHA_BERRY,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 50 %*/ ITEM_NONE,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_POTION,
			/* 30 %*/ ITEM_POTION,
			/* 25 %*/ ITEM_NONE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_RARE_CANDY,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_NONE,
		},
	},
	{
		.species = SPECIES_NUMEL,
		.ability = RAID_ABILITY_RANDOM_1_2,
		.drops =
		{
			/*100 %*/ ITEM_RAWST_BERRY,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 50 %*/ ITEM_NONE,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_POTION,
			/* 30 %*/ ITEM_POTION,
			/* 25 %*/ ITEM_NONE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_RARE_CANDY,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_NONE,
		},
	},
	{
		.species = SPECIES_MANKEY,
		.ability = RAID_ABILITY_RANDOM_1_2,
		.drops =
		{
			/*100 %*/ ITEM_SUPER_REPEL,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 50 %*/ ITEM_NONE,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_POTION,
			/* 30 %*/ ITEM_POTION,
			/* 25 %*/ ITEM_NONE,
			/* 25 %*/ ITEM_STARDUST,
			/*  5 %*/ ITEM_RARE_CANDY,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_NONE,
		},
	},
	{
		.species = SPECIES_RALTS,
		.ability = RAID_ABILITY_RANDOM_1_2,
		.drops =
		{
			/*100 %*/ ITEM_SUPER_POTION,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 50 %*/ ITEM_NONE,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_POTION,
			/* 30 %*/ ITEM_POTION,
			/* 25 %*/ ITEM_NONE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_RARE_CANDY,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_NONE,
		},
	},
};

static struct Raid sRoute1Raids2Star[] =
{
	{
		.species = SPECIES_TRUMBEAK,
		.ability = RAID_ABILITY_RANDOM_1_2,
		.drops =
		{
			/*100 %*/ ITEM_SUPER_POTION,
			/* 80 %*/ ITEM_SITRUS_BERRY,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 50 %*/ ITEM_NONE,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_REVIVE,
			/* 30 %*/ ITEM_REVIVE,
			/* 25 %*/ ITEM_NONE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_RARE_CANDY,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_NONE,
		},
	},
	{
		.species = SPECIES_NOCTOWL,
		.ability = RAID_ABILITY_RANDOM_1_2,
		.drops =
		{
			/*100 %*/ ITEM_LEMONADE,
			/* 80 %*/ ITEM_SITRUS_BERRY,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 50 %*/ ITEM_NONE,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_REVIVE,
			/* 30 %*/ ITEM_REVIVE,
			/* 25 %*/ ITEM_NONE,
			/* 25 %*/ ITEM_BIG_MUSHROOM,
			/*  5 %*/ ITEM_RARE_CANDY,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_NONE,
		},
	},
	{
		.species = SPECIES_HERDIER,
		.ability = RAID_ABILITY_RANDOM_1_2,
		.drops =
		{
			/*100 %*/ ITEM_SODA_POP,
			/* 80 %*/ ITEM_SITRUS_BERRY,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 50 %*/ ITEM_NONE,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_ETHER,
			/* 30 %*/ ITEM_ETHER,
			/* 25 %*/ ITEM_NONE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_RARE_CANDY,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_NONE,
		},
	},
	{
		.species = SPECIES_ARBOK,
		.ability = RAID_ABILITY_RANDOM_1_2,
		.drops =
		{
			/*100 %*/ ITEM_PECHA_BERRY,
			/* 80 %*/ ITEM_SITRUS_BERRY,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 50 %*/ ITEM_NONE,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_REVIVE,
			/* 30 %*/ ITEM_REVIVE,
			/* 25 %*/ ITEM_NONE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_RARE_CANDY,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_NONE,
		},
	},
	{
		.species = SPECIES_NUMEL,
		.ability = RAID_ABILITY_RANDOM_1_2,
		.drops =
		{
			/*100 %*/ ITEM_RAWST_BERRY,
			/* 80 %*/ ITEM_SITRUS_BERRY,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 50 %*/ ITEM_NONE,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_REVIVE,
			/* 30 %*/ ITEM_REVIVE,
			/* 25 %*/ ITEM_NONE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_RARE_CANDY,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_NONE,
		},
	},
	{
		.species = SPECIES_MANKEY,
		.ability = RAID_ABILITY_RANDOM_1_2,
		.drops =
		{
			/*100 %*/ ITEM_SUPER_REPEL,
			/* 80 %*/ ITEM_SITRUS_BERRY,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 50 %*/ ITEM_NONE,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_ETHER,
			/* 30 %*/ ITEM_ETHER,
			/* 25 %*/ ITEM_NONE,
			/* 25 %*/ ITEM_STARDUST,
			/*  5 %*/ ITEM_RARE_CANDY,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_NONE,
		},
	},
	{
		.species = SPECIES_KIRLIA,
		.ability = RAID_ABILITY_RANDOM_1_2,
		.drops =
		{
			/*100 %*/ ITEM_FRESH_WATER,
			/* 80 %*/ ITEM_SITRUS_BERRY,
			/* 80 %*/ ITEM_ORAN_BERRY,
			/* 50 %*/ ITEM_NONE,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_REVIVE,
			/* 30 %*/ ITEM_REVIVE,
			/* 25 %*/ ITEM_NONE,
			/* 25 %*/ ITEM_TINY_MUSHROOM,
			/*  5 %*/ ITEM_RARE_CANDY,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_NONE,
		},
	},
};

static struct Raid sRoute1Raids3Star[] =
{
	{
		.species = SPECIES_TOUCANNON,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_PAMTRE_BERRY,
			/* 80 %*/ ITEM_YACHE_BERRY,
			/* 80 %*/ ITEM_KELPSY_BERRY,
			/* 50 %*/ ITEM_PP_UP,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_SUPER_POTION,
			/* 25 %*/ ITEM_RARE_CANDY,
			/* 25 %*/ ITEM_FLYING_GEM,
			/*  5 %*/ ITEM_KINGS_ROCK,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_NOCTOWL,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_SITRUS_BERRY,
			/* 80 %*/ ITEM_CHARTI_BERRY,
			/* 80 %*/ ITEM_GREPA_BERRY,
			/* 50 %*/ ITEM_BIG_MUSHROOM,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_BALM_MUSHROOM,
			/* 25 %*/ ITEM_RARE_CANDY,
			/* 25 %*/ ITEM_FLYING_GEM,
			/*  5 %*/ ITEM_LEFTOVERS,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_STOUTLAND,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_SITRUS_BERRY,
			/* 80 %*/ ITEM_CHOPLE_BERRY,
			/* 80 %*/ ITEM_TAMATO_BERRY,
			/* 50 %*/ ITEM_MAX_ELIXIR,
			/* 50 %*/ ITEM_NUGGET,
			/* 30 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_RARE_BONE,
			/* 25 %*/ ITEM_RARE_CANDY,
			/* 25 %*/ ITEM_NORMAL_GEM,
			/*  5 %*/ ITEM_LUCKY_EGG,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_ARBOK,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_FIGY_BERRY,
			/* 80 %*/ ITEM_SHUCA_BERRY,
			/* 80 %*/ ITEM_KELPSY_BERRY,
			/* 50 %*/ ITEM_REVIVE,
			/* 50 %*/ ITEM_PECHA_BERRY,
			/* 30 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_NONE,
			/* 25 %*/ ITEM_RARE_CANDY,
			/* 25 %*/ ITEM_POISON_GEM,
			/*  5 %*/ ITEM_BINDING_BAND,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_CAMERUPT,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_SITRUS_BERRY,
			/* 80 %*/ ITEM_PASSHO_BERRY,
			/* 80 %*/ ITEM_HONDEW_BERRY,
			/* 50 %*/ ITEM_NONE,
			/* 50 %*/ ITEM_RAWST_BERRY,
			/* 30 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_NUGGET,
			/* 25 %*/ ITEM_RARE_CANDY,
			/* 25 %*/ ITEM_FIRE_GEM,
			/*  5 %*/ ITEM_ABSORB_BULB,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_PRIMEAPE,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_IAPAPA_BERRY,
			/* 80 %*/ ITEM_PAYAPA_BERRY,
			/* 80 %*/ ITEM_KELPSY_BERRY,
			/* 50 %*/ ITEM_MAX_REPEL,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_STAR_PIECE,
			/* 25 %*/ ITEM_RARE_CANDY,
			/* 25 %*/ ITEM_FIGHTING_GEM,
			/*  5 %*/ ITEM_CHOICE_SCARF,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_GARDEVOIR,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_MAGO_BERRY,
			/* 80 %*/ ITEM_BABIRI_BERRY,
			/* 80 %*/ ITEM_HONDEW_BERRY,
			/* 50 %*/ ITEM_PEARL,
			/* 50 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_NONE,
			/* 30 %*/ ITEM_BIG_MUSHROOM,
			/* 25 %*/ ITEM_RARE_CANDY,
			/* 25 %*/ ITEM_FAIRY_GEM,
			/*  5 %*/ ITEM_MISTY_SEED,
			/*  4 %*/ ITEM_NONE,
			/*  1 %*/ ITEM_BOTTLE_CAP,
		},
	},
};

static struct Raid sRoute1Raids4Star[] =
{
	{
		.species = SPECIES_TOUCANNON,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_LANSAT_BERRY,
			/* 80 %*/ ITEM_YACHE_BERRY,
			/* 80 %*/ ITEM_KELPSY_BERRY,
			/* 50 %*/ ITEM_PP_UP,
			/* 50 %*/ ITEM_SUPER_POTION,
			/* 30 %*/ ITEM_RARE_CANDY,
			/* 30 %*/ ITEM_FLYING_GEM,
			/* 25 %*/ ITEM_HEART_SCALE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_KINGS_ROCK,
			/*  4 %*/ ITEM_BOTTLE_CAP,
			/*  1 %*/ ITEM_GOLD_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_NOCTOWL,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_SITRUS_BERRY,
			/* 80 %*/ ITEM_CHARTI_BERRY,
			/* 80 %*/ ITEM_GREPA_BERRY,
			/* 50 %*/ ITEM_MAX_POTION,
			/* 50 %*/ ITEM_BALM_MUSHROOM,
			/* 30 %*/ ITEM_RARE_CANDY,
			/* 30 %*/ ITEM_FLYING_GEM,
			/* 25 %*/ ITEM_HEART_SCALE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_LEFTOVERS,
			/*  4 %*/ ITEM_BOTTLE_CAP,
			/*  1 %*/ ITEM_GOLD_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_STOUTLAND,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_SITRUS_BERRY,
			/* 80 %*/ ITEM_CHOPLE_BERRY,
			/* 80 %*/ ITEM_TAMATO_BERRY,
			/* 50 %*/ ITEM_MAX_ELIXIR,
			/* 50 %*/ ITEM_RARE_BONE,
			/* 30 %*/ ITEM_RARE_CANDY,
			/* 30 %*/ ITEM_NORMAL_GEM,
			/* 25 %*/ ITEM_HEART_SCALE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_LUCKY_EGG,
			/*  4 %*/ ITEM_BOTTLE_CAP,
			/*  1 %*/ ITEM_GOLD_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_ARBOK,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_FIGY_BERRY,
			/* 80 %*/ ITEM_SHUCA_BERRY,
			/* 80 %*/ ITEM_KELPSY_BERRY,
			/* 50 %*/ ITEM_MAX_REVIVE,
			/* 50 %*/ ITEM_NUGGET,
			/* 30 %*/ ITEM_RARE_CANDY,
			/* 30 %*/ ITEM_POISON_GEM,
			/* 25 %*/ ITEM_HEART_SCALE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_BINDING_BAND,
			/*  4 %*/ ITEM_BOTTLE_CAP,
			/*  1 %*/ ITEM_GOLD_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_CAMERUPT,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_SITRUS_BERRY,
			/* 80 %*/ ITEM_PASSHO_BERRY,
			/* 80 %*/ ITEM_HONDEW_BERRY,
			/* 50 %*/ ITEM_MAX_POTION,
			/* 50 %*/ ITEM_BIG_NUGGET,
			/* 30 %*/ ITEM_RARE_CANDY,
			/* 30 %*/ ITEM_FIRE_GEM,
			/* 25 %*/ ITEM_HEART_SCALE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_ABSORB_BULB,
			/*  4 %*/ ITEM_BOTTLE_CAP,
			/*  1 %*/ ITEM_GOLD_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_PRIMEAPE,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_IAPAPA_BERRY,
			/* 80 %*/ ITEM_PAYAPA_BERRY,
			/* 80 %*/ ITEM_KELPSY_BERRY,
			/* 50 %*/ ITEM_MAX_ETHER,
			/* 50 %*/ ITEM_STAR_PIECE,
			/* 30 %*/ ITEM_RARE_CANDY,
			/* 30 %*/ ITEM_FIGHTING_GEM,
			/* 25 %*/ ITEM_HEART_SCALE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_CHOICE_SCARF,
			/*  4 %*/ ITEM_BOTTLE_CAP,
			/*  1 %*/ ITEM_GOLD_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_GARDEVOIR,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_MAGO_BERRY,
			/* 80 %*/ ITEM_BABIRI_BERRY,
			/* 80 %*/ ITEM_HONDEW_BERRY,
			/* 50 %*/ ITEM_NONE,
			/* 50 %*/ ITEM_BALM_MUSHROOM,
			/* 30 %*/ ITEM_RARE_CANDY,
			/* 30 %*/ ITEM_FAIRY_GEM,
			/* 25 %*/ ITEM_HEART_SCALE,
			/* 25 %*/ ITEM_NONE,
			/*  5 %*/ ITEM_MISTY_SEED,
			/*  4 %*/ ITEM_BOTTLE_CAP,
			/*  1 %*/ ITEM_GOLD_BOTTLE_CAP,
		},
	},
};

static struct Raid sRoute1Raids5Star[] =
{
	{
		.species = SPECIES_TOUCANNON,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_LANSAT_BERRY,
			/* 80 %*/ ITEM_YACHE_BERRY,
			/* 80 %*/ ITEM_KELPSY_BERRY,
			/* 50 %*/ ITEM_PP_UP,
			/* 50 %*/ ITEM_SUPER_POTION,
			/* 30 %*/ ITEM_RARE_CANDY,
			/* 30 %*/ ITEM_FLYING_GEM,
			/* 25 %*/ ITEM_HEART_SCALE,
			/* 25 %*/ ITEM_KINGS_ROCK,
			/*  5 %*/ ITEM_WISHING_PIECE,
			/*  4 %*/ ITEM_BOTTLE_CAP,
			/*  1 %*/ ITEM_GOLD_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_NOCTOWL,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_SITRUS_BERRY,
			/* 80 %*/ ITEM_CHARTI_BERRY,
			/* 80 %*/ ITEM_GREPA_BERRY,
			/* 50 %*/ ITEM_FULL_RESTORE,
			/* 50 %*/ ITEM_BALM_MUSHROOM,
			/* 30 %*/ ITEM_RARE_CANDY,
			/* 30 %*/ ITEM_FLYING_GEM,
			/* 25 %*/ ITEM_HEART_SCALE,
			/* 25 %*/ ITEM_LEFTOVERS,
			/*  5 %*/ ITEM_WISHING_PIECE,
			/*  4 %*/ ITEM_BOTTLE_CAP,
			/*  1 %*/ ITEM_GOLD_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_STOUTLAND,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_SITRUS_BERRY,
			/* 80 %*/ ITEM_CHOPLE_BERRY,
			/* 80 %*/ ITEM_TAMATO_BERRY,
			/* 50 %*/ ITEM_MAX_ELIXIR,
			/* 50 %*/ ITEM_RARE_BONE,
			/* 30 %*/ ITEM_RARE_CANDY,
			/* 30 %*/ ITEM_NORMAL_GEM,
			/* 25 %*/ ITEM_HEART_SCALE,
			/* 25 %*/ ITEM_LUCKY_EGG,
			/*  5 %*/ ITEM_WISHING_PIECE,
			/*  4 %*/ ITEM_BOTTLE_CAP,
			/*  1 %*/ ITEM_GOLD_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_ARBOK,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_FIGY_BERRY,
			/* 80 %*/ ITEM_SHUCA_BERRY,
			/* 80 %*/ ITEM_KELPSY_BERRY,
			/* 50 %*/ ITEM_MAX_REVIVE,
			/* 50 %*/ ITEM_BIG_NUGGET,
			/* 30 %*/ ITEM_RARE_CANDY,
			/* 30 %*/ ITEM_POISON_GEM,
			/* 25 %*/ ITEM_HEART_SCALE,
			/* 25 %*/ ITEM_BINDING_BAND,
			/*  5 %*/ ITEM_WISHING_PIECE,
			/*  4 %*/ ITEM_BOTTLE_CAP,
			/*  1 %*/ ITEM_GOLD_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_CAMERUPT,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_SITRUS_BERRY,
			/* 80 %*/ ITEM_PASSHO_BERRY,
			/* 80 %*/ ITEM_HONDEW_BERRY,
			/* 50 %*/ ITEM_FULL_RESTORE,
			/* 50 %*/ ITEM_BIG_NUGGET,
			/* 30 %*/ ITEM_RARE_CANDY,
			/* 30 %*/ ITEM_FIRE_GEM,
			/* 25 %*/ ITEM_HEART_SCALE,
			/* 25 %*/ ITEM_ABSORB_BULB,
			/*  5 %*/ ITEM_WISHING_PIECE,
			/*  4 %*/ ITEM_BOTTLE_CAP,
			/*  1 %*/ ITEM_GOLD_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_PRIMEAPE,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_IAPAPA_BERRY,
			/* 80 %*/ ITEM_PAYAPA_BERRY,
			/* 80 %*/ ITEM_KELPSY_BERRY,
			/* 50 %*/ ITEM_MAX_ELIXIR,
			/* 50 %*/ ITEM_COMET_SHARD,
			/* 30 %*/ ITEM_RARE_CANDY,
			/* 30 %*/ ITEM_FIGHTING_GEM,
			/* 25 %*/ ITEM_HEART_SCALE,
			/* 25 %*/ ITEM_CHOICE_SCARF,
			/*  5 %*/ ITEM_WISHING_PIECE,
			/*  4 %*/ ITEM_BOTTLE_CAP,
			/*  1 %*/ ITEM_GOLD_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_GARDEVOIR,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_MAGO_BERRY,
			/* 80 %*/ ITEM_BABIRI_BERRY,
			/* 80 %*/ ITEM_HONDEW_BERRY,
			/* 50 %*/ ITEM_MAX_REVIVE,
			/* 50 %*/ ITEM_BALM_MUSHROOM,
			/* 30 %*/ ITEM_RARE_CANDY,
			/* 30 %*/ ITEM_FAIRY_GEM,
			/* 25 %*/ ITEM_HEART_SCALE,
			/* 25 %*/ ITEM_MISTY_SEED,
			/*  5 %*/ ITEM_WISHING_PIECE,
			/*  4 %*/ ITEM_BOTTLE_CAP,
			/*  1 %*/ ITEM_GOLD_BOTTLE_CAP,
		},
	},
	{
		.species = SPECIES_GALLADE,
		.ability = RAID_ABILITY_HIDDEN,
		.drops =
		{
			/*100 %*/ ITEM_WIKI_BERRY,
			/* 80 %*/ ITEM_COBA_BERRY,
			/* 80 %*/ ITEM_GREPA_BERRY,
			/* 50 %*/ ITEM_PP_UP,
			/* 50 %*/ ITEM_RARE_BONE,
			/* 30 %*/ ITEM_RARE_CANDY,
			/* 30 %*/ ITEM_PSYCHIC_GEM,
			/* 25 %*/ ITEM_HEART_SCALE,
			/* 25 %*/ ITEM_SCOPE_LENS,
			/*  5 %*/ ITEM_WISHING_PIECE,
			/*  4 %*/ ITEM_BOTTLE_CAP,
			/*  1 %*/ ITEM_GOLD_BOTTLE_CAP,
		},
	},
};



const struct RaidData gRaidsByMapSection[KANTO_MAPSEC_COUNT][RAID_STAR_COUNT] =
{
	[MAPSEC_ROUTE_1 -  MAPSEC_DYNAMIC] =
	{
		[ONE_STAR_RAID] = {sRoute1Raids1Star, NELEMS(sRoute1Raids1Star)},
		[TWO_STAR_RAID] = {sRoute1Raids2Star, NELEMS(sRoute1Raids2Star)},
		[THREE_STAR_RAID] = {sRoute1Raids3Star, NELEMS(sRoute1Raids3Star)},
		[FOUR_STAR_RAID] = {sRoute1Raids4Star, NELEMS(sRoute1Raids4Star)},
		[FIVE_STAR_RAID] = {sRoute1Raids5Star, NELEMS(sRoute1Raids5Star)},
		[SIX_STAR_RAID] = {sRoute1Raids5Star, NELEMS(sRoute1Raids5Star)},
	},
};

